GET http://localhost:3014/

###
POST http://localhost:3014/add-movie
Content-Type: application/json

{
    "titulo": "Big Mac e Boder radius, o romance",
    "genero": "Romance e Drama",
    "duracao": 169,
    "classificacao": "27 anos"
}

###
GET http://localhost:3014/movies

###
PUT http://localhost:3014/update-movie/1
Content-Type: application/json

{
    "titulo": "Shrek 2 - Versão Estendida",
    "genero": "Animação/Comédia",
    "duracao": 105,
    "classificacao": "Livre"
}

###
DELETE http://localhost:3014/delete-movie/3